/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_tykvin_jni_nativeinvokers_HelloWorld */

#ifndef _Included_ru_tykvin_jni_nativeinvokers_HelloWorld
#define _Included_ru_tykvin_jni_nativeinvokers_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_tykvin_jni_nativeinvokers_HelloWorld
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_tykvin_jni_nativeinvokers_HelloWorld_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
