/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_tykvin_jni_nativeinvokers_QTViewHelloWorld */

#ifndef _Included_ru_tykvin_jni_nativeinvokers_QTViewHelloWorld
#define _Included_ru_tykvin_jni_nativeinvokers_QTViewHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_tykvin_jni_nativeinvokers_QTViewHelloWorld
 * Method:    showView
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_tykvin_jni_nativeinvokers_QTViewHelloWorld_showView
  (JNIEnv *, jobject);

/*
 * Class:     ru_tykvin_jni_nativeinvokers_QTViewHelloWorld
 * Method:    addTileN
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ru_tykvin_jni_nativeinvokers_QTViewHelloWorld_addTileN
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     ru_tykvin_jni_nativeinvokers_QTViewHelloWorld
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_tykvin_jni_nativeinvokers_QTViewHelloWorld_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
