/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_tykvin_jni_nativeinvokers_Win32HelloWorld */

#ifndef _Included_ru_tykvin_jni_nativeinvokers_Win32HelloWorld
#define _Included_ru_tykvin_jni_nativeinvokers_Win32HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_tykvin_jni_nativeinvokers_Win32HelloWorld
 * Method:    getForegroundHwnd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_tykvin_jni_nativeinvokers_Win32HelloWorld_getForegroundHwnd
  (JNIEnv *, jobject);

/*
 * Class:     ru_tykvin_jni_nativeinvokers_Win32HelloWorld
 * Method:    showWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_tykvin_jni_nativeinvokers_Win32HelloWorld_showWindow
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
