/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_tykvin_jni_QTHelloWorld */

#ifndef _Included_ru_tykvin_jni_QTHelloWorld
#define _Included_ru_tykvin_jni_QTHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_tykvin_jni_QTHelloWorld
 * Method:    showWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_tykvin_jni_QTHelloWorld_showWindow
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
